default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: garage_development

test:
  <<: *default
  database: garage_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
